MAIN/urls.py
from django.urls import path
from .views import user_cart, index, specific_product,checkout, brand_page, category_page, search_results



app_name = "MAIN"

urlpatterns = [
    path("",index,name="home"),
    path("product/<int:pk>",specific_product,name="product"),
    path("cart",user_cart,name="cart"),
    path("checkout/<int:order_id>",checkout,name="checkout"),
    path("brand/<str:brand>",brand_page,name="brand"),
    path("category/<str:category>",category_page,name="category"),
    path("search",search_results,name="search")


]

USERS/urls.py
from django.urls import path, include
from .views import signup,login_view,subscribe,logout_view, google_login,google_callback


app_name = "auth"
urlpatterns = [
    path("register",signup,name="register"),
    path("login",login_view,name="login"),
    path("logout",logout_view,name="logout_user"),
    path("subscribe",subscribe,name="subscribe") ,
    path("login/google/",google_login,name="google_login"),
    path('login/google/callback/', google_callback, name='google_callback'),
    # path('password_reset/', include('django.contrib.auth.urls'), name="recovery")
]

chirpyStores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from MAIN.views import add_to_cart, remove_from_cart, update_order_item, save_billing_info
# from django.conf.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/",include("USERS.urls")),
    path("",include("MAIN.urls")),
    path("payment/",include("Payment.urls"))

]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

htmx_patterns = [
    path("add_to_cart",add_to_cart,name="add_to_cart"),
    path("remove/<int:pk>/",remove_from_cart,name="remove_from_cart"),
    path("update/<int:pk>",update_order_item,name="update_cart"),
    path("add_billing_info",save_billing_info,name="new_billing_info")
    ]

urlpatterns += htmx_patterns

templates/partials/add_new_billing_details.html
                <form>
                    <div>
                        <div class="col-lg-9 mt-6 mx-auto">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <label>First Name *</label>
                                        <input type="text" class="form-control" required>
                                    </div><!-- End .col-sm-6 -->

                                    <div class="col-sm-6">
                                        <label>Last Name *</label>
                                        <input type="text" class="form-control" required>
                                    </div><!-- End .col-sm-6 -->
                                </div><!-- End .row -->


                                <label>Street address *</label>
                                <input type="text" class="form-control" placeholder="House number and Street name" required>
                                <input type="text" class="form-control" placeholder="Appartments, suite, unit etc ..." required>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <label>State *</label>
                                        <input type="text" class="form-control" required>
                                    </div><!-- End .col-sm-6 -->

                                    <div class="col-sm-6">
                                        <label>City *</label>
                                        <input type="text" class="form-control" required>
                                    </div><!-- End .col-sm-6 -->
                                </div><!-- End .row -->

                                <div class="row">
                                    {% comment %} <div class="col-sm-6">
                                        <label>Postcode / ZIP *</label>
                                        <input type="text" class="form-control" required>
                                    </div><!-- End .col-sm-6 --> {% endcomment %}

                                    <div class="col-sm-6">
                                        <label>Phone *</label>
                                        <input type="tel" class="form-control" required>
                                    </div><!-- End .col-sm-6 -->
                                </div><!-- End .row -->

                                <label>Email address *</label>
                                <input type="email" class="form-control" required>

                                {% comment %} <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="checkout-create-acc">
                                    <label class="custom-control-label" for="checkout-create-acc">Create an account?</label>
                                </div><!-- End .custom-checkbox --> {% endcomment %}

                                {% comment %} <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="checkout-diff-address">
                                    <label class="custom-control-label" for="checkout-diff-address">Ship to a different address?</label>
                                </div><!-- End .custom-checkbox --> {% endcomment %}

                                <label>Order notes (optional)</label>
                                <textarea class="form-control" cols="30" rows="4" placeholder="Notes about your order, e.g. special notes for delivery"></textarea>
                        </div><!-- End .col-lg-9 -->
                        <div>
                            <button 
                                class="btn btn-primary btn-block mx-auto" 
                                hx-post = "{% url 'new_billing_info' %}"
                                hx-headers='{ "X-CSRFToken": "{{ csrf_token }}" }'
                                hx-vals = '{
                                    "from_modal":true
                                }'
                                hx-target = '.delivery-info'

                                >save</button>
                        </div>
                    </div>
                </form>

templates/partials/cart-count.html
<div>
    {{quantity}}
</div>

templates/partials/cart-item.html
<tr id="product-info-{{order_item.pk}}">
    <td class="product-col">
        <div class="product">
            <figure class="product-media">
                <a href="#">
                    <img src=" {{ order_item.product.image.url }}" alt="Product image">
                </a>
            </figure>

            <h3 class="product-title">
                <a href="{% url 'MAIN:product' pk=order_item.product.pk %}">{{order_item.product.name}}</a>
            </h3><!-- End .product-title -->
        </div><!-- End .product -->
    </td>
    <td class="price-col" style="color:black"><span style="text-decoration: line-through; color: black; padding-right: 2px; font-size: 0.8em;">N</span><span id="productPrice">{{order_item.product.price|intcomma }}</span></td>
    <td class="quantity-col">
        <div class="cart-product-quantity"                                                     
>
            <input type="number" class="form-control" value="{{order_item.quantity}}"
                    hx-post = "/update/{{order_item.pk}}"
                    hx-target = "#product-info-{{order_item.pk}}"
                    hx-trigger = "change"
                    hx-delay= "2s"
                    hx-headers='{ "X-CSRFToken": "{{ csrf_token }}" }'
                    hx-vals =  'js:{ quantity: getQuantity({{order_item.pk}})}'   
                    onclick="calculateNewTotal()"  
                    id="quantity-{{order_item.pk}}" min="1" max="10" step="1" data-decimals="0" required>
        </div><!-- End .cart-product-quantity -->
    </td>
    <td class="total-col" style="color:black; font-size:1.3em; font-weight:600;"><span style="text-decoration: line-through; color: black; padding-right: 2px; font-size: 0.8em;">N</span>{{order_item.line_total|intcomma}}</td>
    <td 
        hx-delete="{% url 'remove_from_cart' pk=order_item.id %}"
        hx-confirm="Are you sure you want to remove this product from your cart ?"
        hx-headers='{ "X-CSRFToken": "{{ csrf_token }}" }'
        hx-target=".cart"


        class="remove-col"
    >
        <button 
            class="btn-remove"
            {% comment %} hx-get="{% url 'remove_from_cart' pk=order_item.pk %}"
            hx-confirm="Are you sure you want to remove this product from your cart ?" 
            hx-target=".cart-items" 
            hx-headers='{ "X-CSRFToken": "{{ csrf_token }}" }'                                             {% endcomment %}
        >
            <i class="icon-close" style="cursor: pointer; color:pink;"></i>
        </button>
    </td>
</tr>

templates/partials/delivery_info.html
<div class="delivery-info">
    <form method="post" id="deliveryInfoForm" onsubmit="return validateForm()">
        {% csrf_token %}
            {% for detail in delivery_details %}

                <div class="col-lg-6 col-md-12" style="box-shadow:black;">
                    <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Billing Information-{{detail.pk}}</h5>
                        <p class="card-text">{{detail.first_name}} {{detail.last_name}}<br>{{detail.street_address}}<br>{{detail.city}}, {{detail.state}}<br>Nigeria</p>
                        <!-- Checkbox field for choice -->
                        <div class="form-check float-right">

                            <input class="form-check-input choice-checkbox" value="{{detail.id}}" name="delivery_info" type="checkbox" id="delivery_info{{ detail.id }}" {% if forloop.first %} checked {% endif %}>
                            <label class="form-check-label" for="checkbox"></label>
                        </div>
                    </div>
                    </div>
                </div>

            
            {% endfor %}
    </form>
        <!-- Button column -->
            <button style="width: 20px; height:50px; margin:10px;" type="button" class="btn btn-primary btn-block"
            data-toggle={% if request.user.is_authenticated %} "modal" {% else %} None {% endif %}
            data-target={% if request.user.is_authenticated %}"#new-billing-info-modal"{% else %} None {% endif %}
            >+</button>
 </div>

templates/partials/sign-in.html
<div class="tab-pane fade show active" id="signin" role="tabpanel" aria-labelledby="signin-tab">
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <p style="color: red;">{{ message }}</p>
        {% endif %}
    {% endfor %}
    <form action="{% url 'auth:login'%}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="signin-email" style="font-weight: bold;">Email address *</label>
            <input type="text" class="form-control" id="singin-email" name="signin-email" required>
        </div><!-- End .form-group -->

        <div class="form-group">
            <label for="signin-password" style="font-weight: bold;">Password *</label>
            <input type="password" class="form-control" id="singin-password" name="signin-password" required>
        </div><!-- End .form-group -->

        <div class="form-footer">
            <button type="submit" class="btn btn-outline-primary-2">
                <span>LOG IN</span>
                <i class="icon-long-arrow-right"></i>
            </button>

            {% comment %} <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="signin-remember">
                <label class="custom-control-label" for="signin-remember">Remember Me</label>
            </div><!-- End .custom-checkbox --> {% endcomment %}

            <a href="/auth/password_reset/password_reset/" class="forgot-link">Forgot Your Password?</a>
        </div><!-- End .form-footer -->
    </form>

    {% comment %} O-AUTH {% endcomment %}
     <div class="form-choice">
        <p class="text-center">or sign in with</p>
        <div class="col">
            <div>
                <a href="{% url 'auth:google_login' %}" class="btn btn-login btn-g">
                    <i class="icon-google"></i>
                    Login With Google
                </a>
            </div><!-- End .col-6 -->
        </div><!-- End .row -->
    </div><!-- End .form-choice -->
</div><!-- .End .tab-pane -->

templates/partials/sign-up.html
<div class="tab-pane fade" id="register" role="tabpanel" aria-labelledby="register-tab">
    <form action="{% url 'auth:register'%}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="register-email" style="font-weight: bold;">Your email address *</label>
            <input type="email" class="form-control" id="register-email" name="register-email" required>
        </div><!-- End .form-group -->

        <div class="form-group">
            <label for="register-email" style="font-weight: bold;">Phone Number  (optional)* </label>
            <input type="phone2numeric" class="form-control" id="register-mobile-number" name="phone-number" >
        </div><!-- End .form-group -->


        <div class="form-group">
            <label for="register-password" style="font-weight: bold;">Password *</label>
            <input type="password" class="form-control" id="register-password" name="register-password" required>
        </div><!-- End .form-group -->

        <div class="form-footer">
            <button type="submit" class="btn btn-outline-primary-2">
                <span>SIGN UP</span>
                <i class="icon-long-arrow-right"></i>
            </button>

            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="register-policy" required>
                <label class="custom-control-label" for="register-policy">I agree to the <a href="#">privacy policy</a> *</label>
            </div><!-- End .custom-checkbox -->
        </div><!-- End .form-footer -->
    </form>
     {% comment %} O-AUTH {% endcomment %}
     <div class="form-choice">
        <p class="text-center">or sign in with</p>
        <div class="col">
            <div>
                <a href="{% url 'auth:google_login' %}" class="btn btn-login btn-g">
                    <i class="icon-google"></i>
                    Login With Google
                </a>
            </div><!-- End .col-6 -->
        </div><!-- End .row -->
    </div><!-- End .form-choice -->
    {% comment %} O-AUTH {% endcomment %}
    {% comment %} <div class="form-choice">
        <p class="text-center">or sign in with</p>
        <div class="row">
            <div class="col-sm-6">
                <a href="#" class="btn btn-login btn-g">
                    <i class="icon-google"></i>
                    Login With Google
                </a>
            </div><!-- End .col-6 -->
            <div class="col-sm-6">
                <a href="#" class="btn btn-login  btn-f">
                    <i class="icon-facebook-f"></i>
                    Login With Facebook
                </a>
            </div><!-- End .col-6 -->
        </div><!-- End .row -->
    </div><!-- End .form-choice --> {% endcomment %}
</div><!-- .End .tab-pane -->