MAIN/urls.py
from django.urls import path
from .views import user_cart, index, specific_product,checkout, brand_page, category_page, search_results



app_name = "MAIN"

urlpatterns = [
    path("",index,name="home"),
    path("product/<int:pk>",specific_product,name="product"),
    path("cart",user_cart,name="cart"),
    path("checkout/<int:order_id>",checkout,name="checkout"),
    path("brand/<str:brand>",brand_page,name="brand"),
    path("category/<str:category>",category_page,name="category"),
    path("search",search_results,name="search")


]

USERS/urls.py
from django.urls import path, include
from .views import signup,login_view,subscribe,logout_view, google_login,google_callback


app_name = "auth"
urlpatterns = [
    path("register",signup,name="register"),
    path("login",login_view,name="login"),
    path("logout",logout_view,name="logout_user"),
    path("subscribe",subscribe,name="subscribe") ,
    path("login/google/",google_login,name="google_login"),
    path('login/google/callback/', google_callback, name='google_callback'),
    # path('password_reset/', include('django.contrib.auth.urls'), name="recovery")
]

chirpyStores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from MAIN.views import add_to_cart, remove_from_cart, update_order_item, save_billing_info
# from django.conf.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/",include("USERS.urls")),
    path("",include("MAIN.urls")),
    path("payment/",include("Payment.urls"))

]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

htmx_patterns = [
    path("add_to_cart",add_to_cart,name="add_to_cart"),
    path("remove/<int:pk>/",remove_from_cart,name="remove_from_cart"),
    path("update/<int:pk>",update_order_item,name="update_cart"),
    path("add_billing_info",save_billing_info,name="new_billing_info")
    ]

urlpatterns += htmx_patterns

templates/login.html
{% extends 'base_layout.html' %}


{% block icons %}
<div class="header-search" style="margin-left: 180px;">
    <a href="#" class="search-toggle" role="button"><i class="icon-search"></i></a>
    <form action="#" method="get">
        <div class="header-search-wrapper">
            <label for="q" class="sr-only">Search</label>
            <input type="search" class="form-control" name="q" id="q" placeholder="Search in..." required>
        </div><!-- End .header-search-wrapper -->
    </form>
</div><!-- End .header-search -->

<a href="wishlist.html" class="wishlist-link">
    <i class="icon-heart-o"></i>
        <span class="wishlist-count">3</span>
</a>

<div class="dropdown cart-dropdown">
    <a href="{% url 'MAIN:cart' %}" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
        <i class="icon-shopping-cart"></i>
        <span class="cart-count" id="cart-count">
            {% if quantity %}
                {{quantity}}
            {% else%}
                0
            {% endif %}
            </span>
    </a>


</div><!-- End .cart-dropdown -->
{% endblock icons %}

{% block auth %}
    <div ></div>
{% endblock auth %}


{% block content %}
<main class="main">

    <div class="login-page bg-image pt-8 pb-8 pt-md-12 pb-md-12 pt-lg-17 pb-lg-17" style="background-image: url('assets/images/backgrounds/login-bg.jpg')">
        <div class="container">
            <div class="form-box">
                <div class="form-tab">
                    <ul class="nav nav-pills nav-fill" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="signin-tab-2" data-toggle="tab" href="#signin-2" role="tab" aria-controls="signin-2" aria-selected="false">Sign In</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                                <p style="color: red; margin-top: 12px;">{{ message }}</p>
                            {% endif %}
                        {% endfor %}

                        <div class="tab-pane fade show active" id="signin-2" role="tabpanel" aria-labelledby="signin-tab-2">
                            <form action="{% url 'auth:login'%}" method="post">
                                {% csrf_token %}
                        
                                <div class="form-group">
                                    <label for="signin-email" style="font-weight: bold;">Email address *</label>
                                    <input type="text" class="form-control" id="singin-email" name="signin-email" required>
                                </div><!-- End .form-group -->
                        
                                <div class="form-group">
                                    <label for="signin-password" style="font-weight: bold;">Password *</label>
                                    <input type="password" class="form-control" id="singin-password" name="signin-password" required>
                                </div><!-- End .form-group -->
                        
                                <div class="form-footer">
                                    <button type="submit" class="btn btn-outline-primary-2">
                                        <span>LOG IN</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </button>
                        
                                    {% comment %} <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="signin-remember">
                                        <label class="custom-control-label" for="signin-remember">Remember Me</label>
                                    </div><!-- End .custom-checkbox --> {% endcomment %}
                        
                                    <a href="/auth/password_reset/password_reset/" class="forgot-link">Forgot Your Password?</a>
                                </div><!-- End .form-footer -->
                            </form>
                               {% comment %} O-AUTH {% endcomment %}
                        <div class="form-choice">
                            <p class="text-center">or sign in with</p>
                            <div class="col">
                                <div>
                                    <a href="{% url 'auth:google_login' %}" class="btn btn-login btn-g">
                                        <i class="icon-google"></i>
                                        Login With Google
                                    </a>
                                </div><!-- End .col-6 -->
                            </div><!-- End .row -->
                        </div><!-- End .form-choice -->
                        </div><!-- .End .tab-pane -->
                        <div class="tab-pane fade" id="register-2" role="tabpanel" aria-labelledby="register-tab-2">
                            <form action="{% url 'auth:register'%}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="register-email" style="font-weight: bold;">Your email address *</label>
                                    <input type="email" class="form-control" id="register-email" name="register-email" required>
                                </div><!-- End .form-group -->
                        
                                <div class="form-group">
                                    <label for="register-email" style="font-weight: bold;">Phone Number  (optional)* </label>
                                    <input type="phone2numeric" class="form-control" id="register-mobile-number" name="phone-number" >
                                </div><!-- End .form-group -->
                        
                        
                                <div class="form-group">
                                    <label for="register-password" style="font-weight: bold;">Password *</label>
                                    <input type="password" class="form-control" id="register-password" name="register-password" required>
                                </div><!-- End .form-group -->
                        
                                <div class="form-footer">
                                    <button type="submit" class="btn btn-outline-primary-2">
                                        <span>SIGN UP</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </button>
                        
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="register-policy" required>
                                        <label class="custom-control-label" for="register-policy">I agree to the <a href="#">privacy policy</a> *</label>
                                    </div><!-- End .custom-checkbox -->
                                </div><!-- End .form-footer -->
                            </form>
                                 {% comment %} O-AUTH {% endcomment %}
                            <div class="form-choice">
                                <p class="text-center">or sign in with</p>
                                <div class="col">
                                    <div>
                                        <a href="{% url 'auth:google_login' %}" class="btn btn-login btn-g">
                                            <i class="icon-google"></i>
                                            Login With Google
                                        </a>
                                    </div><!-- End .col-6 -->
                                </div><!-- End .row -->
                            </div><!-- End .form-choice -->
                        </div><!-- .End .tab-pane -->
                    </div><!-- End .tab-content -->
                </div><!-- End .form-tab -->
            </div><!-- End .form-box -->
        </div><!-- End .container -->
    </div><!-- End .login-page section-bg -->
</main><!-- End .main -->
{% endblock content %}

templates/register.html
{% extends 'base_layout.html' %}


{% block icons %}
<div class="header-search" style="margin-left: 180px;">
    <a href="#" class="search-toggle" role="button"><i class="icon-search"></i></a>
    <form action="#" method="get">
        <div class="header-search-wrapper">
            <label for="q" class="sr-only">Search</label>
            <input type="search" class="form-control" name="q" id="q" placeholder="Search in..." required>
        </div><!-- End .header-search-wrapper -->
    </form>
</div><!-- End .header-search -->

<a href="wishlist.html" class="wishlist-link">
    <i class="icon-heart-o"></i>
        <span class="wishlist-count">3</span>
</a>

<div class="dropdown cart-dropdown">
    <a href="{% url 'MAIN:cart' %}" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
        <i class="icon-shopping-cart"></i>
        <span class="cart-count" id="cart-count">10</span>

    </a>


</div><!-- End .cart-dropdown -->
{% endblock icons %}

{% block auth %}
    <div ></div>
{% endblock auth %}


{% block content %}
<main class="main">

    <div class="login-page bg-image pt-8 pb-8 pt-md-12 pb-md-12 pt-lg-17 pb-lg-17" style="background-image: url('assets/images/backgrounds/login-bg.jpg')">
        <div class="container">
            <div class="form-box">
                <div class="form-tab">
                    <ul class="nav nav-pills nav-fill" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active " id="register-tab-2" data-toggle="tab" href="#register-2" role="tab" aria-controls="register-2" aria-selected="true">Register</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                                <p style="color: red; margin-top: 12px;">{{ message }}</p>
                            {% endif %}
                        {% endfor %}

                        
                        <div class="tab-pane fade show active" id="register-2" role="tabpanel" aria-labelledby="register-tab-2">
                            <form action="{% url 'auth:register'%}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="register-email" style="font-weight: bold;">Your email address *</label>
                                    <input type="email" class="form-control" id="register-email" name="register-email" required>
                                </div><!-- End .form-group -->
                        
                                <div class="form-group">
                                    <label for="register-email" style="font-weight: bold;">Phone Number  (optional)* </label>
                                    <input type="phone2numeric" class="form-control" id="register-mobile-number" name="phone-number" >
                                </div><!-- End .form-group -->
                        
                        
                                <div class="form-group">
                                    <label for="register-password" style="font-weight: bold;">Password *</label>
                                    <input type="password" class="form-control" id="register-password" name="register-password" required>
                                </div><!-- End .form-group -->
                        
                                <div class="form-footer">
                                    <button type="submit" class="btn btn-outline-primary-2">
                                        <span>SIGN UP</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </button>
                        
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="register-policy" required>
                                        <label class="custom-control-label" for="register-policy">I agree to the <a href="#">privacy policy</a> *</label>
                                    </div><!-- End .custom-checkbox -->
                                </div><!-- End .form-footer -->
                            </form>
                                 {% comment %} O-AUTH {% endcomment %}
                            <div class="form-choice">
                                <p class="text-center">or sign in with</p>
                                <div class="col">
                                    <div>
                                        <a href="{% url 'auth:google_login' %}" class="btn btn-login btn-g">
                                            <i class="icon-google"></i>
                                            Login With Google
                                        </a>
                                    </div><!-- End .col-6 -->
                                </div><!-- End .row -->
                            </div><!-- End .form-choice -->
                        </div><!-- .End .tab-pane -->
                    </div><!-- End .tab-content -->
                </div><!-- End .form-tab -->
            </div><!-- End .form-box -->
        </div><!-- End .container -->
    </div><!-- End .login-page section-bg -->
</main><!-- End .main -->
{% endblock content %}